
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package tarea3.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int para = 2;
  public static final int punto = 4;
  public static final int cadena = 7;
  public static final int error = 1;
  public static final int puntoycoma = 5;
  public static final int parc = 3;
  public static final int EOF = 0;
  public static final int imprimir = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "para",
  "parc",
  "punto",
  "puntoycoma",
  "imprimir",
  "cadena"
  };
}

